service:
  name: lambda-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-express

provider:
  name: aws
  runtime: nodejs8.10

functions:
  lambda-typescript:
    handler: handler.api
    events:
      - http:
          path: /{proxy+}
          method: ANY
